services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123

  phpmyadmin:
    image: phpmyadmin
    ports: 
      - "8000:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
